language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: CI0P/pEJISSa0OKhQaRrIB52PrwyYAVzkc9jq6R0W7cb2aJ1TSk+EwM9TXPdaxVBvwh7qniXajCypl/q7xpFxBCcSGVrXDWUlCgOUtOZmS191yteuI+4i6HfxkV07D2mA0Rypo0yAVTNlifYWadeezaE63f/yfwjWCg949KdgH68QXlNPXfj2tOiLTwx6ISZgmF3mp10tb7zKdBvni2XDgbdbtrYz1wR6Lww5W9dm+WpEd5UETxktoH/3bn3xCk0qzDYWX0060t+kBvb9tvpYyTm7smoloxtTbIIIGk7NMM/Otii2FRAV3JNL85rZOpUyHbUaYFUblOMdXR2j51dON9hOrPYFl2wupRL0IaI8v1j0HRPvLbKzQqZ40rA2wCn8S06f1h8uwJbCHCieXhsrqBtdHIXu1Skg1kG2FHs/ZghR5kx5skvAW2CFI3I3PdxHpklC3GNcU561jZEZhYweSNOoC0hntpzyc+a6GYImccaQa382WD0Bgl0cN8MHFsnIoUSKozotMWUTsBwliVZv98LfcVekkoD0BXG2Lfm8eoQeJjG4PmqtGvyRfvyFV6F5oq63sNwxSbxb9gZuICn4KY5iYAla8UfTmxk5JhtT8K6cW5NosBAAkDjV+yTA/zw44LNfTOR6D6i7hyvVEaDYyZbJaf8w8ryAnEwJVndjJM=
  app: evening-reef-11101
  on:
    repo: calysabean/travisCiHerukoExRestaurantApp
